FROM flink:2.0.1-java17

RUN wget -q -O /opt/flink/lib/flink-metrics-prometheus-2.0.1.jar \
    https://repo1.maven.org/maven2/org/apache/flink/flink-metrics-prometheus/2.0.1/flink-metrics-prometheus-2.0.1.jar
