FROM flink:1.18-java11

RUN wget -q -O /opt/flink/lib/flink-metrics-prometheus-1.18.1.jar \
    https://repo1.maven.org/maven2/org/apache/flink/flink-metrics-prometheus/1.18.1/flink-metrics-prometheus-1.18.1.jar
